apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1-service
spec:
  selector:
    app: kafka-broker
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-2-service
spec:
  selector:
    app: kafka-broker
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-3-service
spec:
  selector:
    app: kafka-broker
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: LoadBalancer
