apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['broker-id']
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: {zookeeper-service}:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://{load-balancer-ip}:9092
        command:
         - "sh"
         - "-c"
         - |
           POD_NUMBER=$(hostname | awk -F'-' '{print $NF}')
           next_pod_number=$((POD_NUMBER + 2))
           new_advertised_listeners="advertised.listeners=PLAINTEXT://172.20.0.$next_pod_number:9092"
           sed -i "s/^broker\.id=.*/broker\.id=$POD_NUMBER/" /opt/kafka/config/server.properties
           sed -i "s/^zookeeper\.connect=.*/zookeeper\.connect={zookeeper-service}:2181/" /opt/kafka/config/server.properties
           sed -i "s/^#listeners=PLAINTEXT:\/\/:9092/listeners=PLAINTEXT:\/\/:9092/" /opt/kafka/config/server.properties
           sed -i "s/^#advertised.listeners=PLAINTEXT:\/\/your\.host\.name:9092/advertised.listeners=PLAINTEXT:\/\/172.20.0.$next_pod_number:9092/" /opt/kafka/config/server.properties
           sleep 2
           exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-broker
        ports:
          - containerPort: 9092
        volumeMounts:
          - name: logs
            mountPath: /kafka-logs
            subPath: logs
          - name: metadata-volume
            mountPath: /metadata
            readOnly: true
      volumes:
        - name: metadata-volume
          downwardAPI:
            items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
  volumeClaimTemplates:
    - metadata:
        name: logs
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

